import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const Ubuntus = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-Ubuntu",
});

export const metadata: Metadata = {
  title: "Breado",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Ubuntus.variable} antialiased`}>{children}</body>
    </html>
  );
}
